config/routes.rb
Stratos::Application.routes.draw do
  resources :report_items

  resources :groups

  resources :reports

  devise_for :users

  root :to => "reports#index"
end

app/models/group.rb
class Group < ActiveRecord::Base

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :group
  has_many :report_items

  scope :for_user, lambda{|user| {:conditions=>{:group_id => user.group.id }} }
end

app/models/report_item.rb
class ReportItem < ActiveRecord::Base
  belongs_to :report
  belongs_to :user
  validates_presence_of :title, :user, :report
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :group

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :group_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
end

app/controllers/report_items_controller.rb
class ReportItemsController < ApplicationController

  # GET /report_items/1/edit
  def edit
    @report_item = ReportItem.find(params[:id])
    render action: "edit" , layout: false 
  end

  # POST /report_items
  # POST /report_items.json
  def create
    @report_item = ReportItem.new(params[:report_item])

    respond_to do |format|
      if @report_item.save
        format.html { redirect_to @report_item.report, notice: 'Report item was successfully created.' }
        format.json { render json: @report_item, status: :created, location: @report_item }
      else
        format.html { redirect_to @report_item.report }
        format.json { render json: @report_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /report_items/1
  # PUT /report_items/1.json
  def update
    @report_item = ReportItem.find(params[:id])

    respond_to do |format|
      if @report_item.update_attributes(params[:report_item])
        format.html { redirect_to @report_item.report, notice: 'Report item was successfully updated.' }
        format.json { head :ok }
      else
        format.html { redirect_to @report_item.report }
        format.json { render json: @report_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /report_items/1
  # DELETE /report_items/1.json
  def destroy
    @report_item = ReportItem.find(params[:id])
    @report_item.destroy

    respond_to do |format|
      format.html { redirect_to @report_item.report }
      format.json { head :ok }
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.for_user(current_user).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.for_user(current_user).find(params[:id])

    @report_items = @report.report_items
    @report_item = ReportItem.new
    @report_item.user = current_user
    @report_item.report = @report
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new
    @report.title = "#{current_user.group.name + '`s'} report for the week of #{DateTime.now.beginning_of_week.strftime('%d %B %Y')}"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.for_user(current_user).find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @last_report = Report.for_user(current_user).last
    @report = Report.new(params[:report])
    @report.group = current_user.group
    
    respond_to do |format|
      if @report.save
        @last_report.report_items.all(:conditions=>{:kind=>"Next Week"}).each do |report_item|
          new_report_item = report_item.dup
          new_report_item.kind = "This Week"
          new_report_item.save
          @report.report_items << new_report_item
        end if @last_report.report_items

        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.for_user(current_user).find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.for_user(current_user).find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/report_items_helper.rb
module ReportItemsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= link_to 'Show', group %></td>
    <td><%= link_to 'Edit', edit_group_path(group) %></td>
    <td><%= link_to 'Destroy', group, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @group.name %>
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Stratos</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <style>

html, body {
  background-color: #eee;
}
body {
  padding-top: 40px; /* 40px to make the container go all the way to the bottom of the topbar */
}
.container > footer p {
  text-align: center; /* center align it with the container */
}
.container {
  width: 820px; /* downsize our container to make the content feel a bit tighter and more cohesive. NOTE: this removes two full columns from the grid, meaning you only go to 14 columns and not 16. */
}

/* The white background content wrapper */
.content {
  background-color: #fff;
  padding: 20px;
  margin: 0 -20px; /* negative indent the amount of the padding to maintain the grid system */
  -webkit-border-radius: 0 0 6px 6px;
     -moz-border-radius: 0 0 6px 6px;
          border-radius: 0 0 6px 6px;
  -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
     -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
          box-shadow: 0 1px 2px rgba(0,0,0,.15);
}

/* Page header tweaks */
.page-header {
  background-color: #f5f5f5;
  padding: 20px 20px 10px;
  margin: -20px -20px 20px;
}

/* Styles you shouldn't keep as they are for displaying this base example only */
.content .span10,
.content .span4 {
  min-height: 500px;
}
/* Give a quick and non-cross-browser friendly divider */
.content .span4 {
  margin-left: 0;
  padding-left: 19px;
  border-left: 1px solid #eee;
}

.topbar .btn {
  border: 0;
}
  </style>
</head>
<body>

    <div class="topbar">
      <div class="fill">
        <div class="container">
          <a class="brand" href="/">Weekly Reports</a>
          <ul class="nav">
            <li class="active"><a href="/reports">Reports</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">


      <div class="content">
        <div class="page-header">
          <%= yield :page_header%>
        </div>
        <%= yield %>
      </div>

      <footer>
        <p>&copy; Mindvalley Technology 2011</p>
      </footer>

    </div> <!-- /container -->
    


</body>
</html>

app/views/report_items/_form.html.erb
<%= simple_form_for(@report_item , :wrapper => :inline) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.association :user, :prompt => false , :label => "I am" %>
    <%= f.input :kind, :collection=>['This Week','Next Week'], :label=> "For", :prompt => false%>
    <%= f.input :title,:input_html => {:class=>'xlarge',:style=>"z-index:12000"}, :label => "One of my task is" %>
    
  </div>

  <div class="actions">
    <%= f.button :submit%>
  </div>
  <%= f.input :report_id, :as=> :hidden%>
<% end %>

app/views/report_items/edit.html.erb
<%= render 'form' %>

<%= link_to 'Delete this!', @report_item, confirm: 'Are you sure?', method: :delete, class:"btn danger" %>

app/views/report_items/index.html.erb
<h1>Listing report_items</h1>

<table>
  <tr>
    <th>Title</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @report_items.each do |report_item| %>
  <tr>
    <td><%= report_item.title %></td>
    <td><%= report_item.user_id %></td>
    <td><%= link_to 'Show', report_item %></td>
    <td><%= link_to 'Edit', edit_report_item_path(report_item) %></td>
    <td><%= link_to 'Destroy', report_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report item', new_report_item_path %>

app/views/report_items/new.html.erb
<h1>New report_item</h1>

<%= render 'form' %>

<%= link_to 'Back', report_items_path %>

app/views/report_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @report_item.title %>
</p>

<p>
  <b>User:</b>
  <%= @report_item.user_id %>
</p>


<%= link_to 'Edit', edit_report_item_path(@report_item) %> |
<%= link_to 'Back', report_items_path %>

app/views/reports/_form.html.erb
<%= simple_form_for(@report, :wrapper => :stacked) do |f| %>
  <%= f.error_notification %>
  
  <div class="inputs">
    <%= f.input :title, :input_html => {:class=>'xxlarge'} %>
    <%= f.input :notes, :input_html => {:class=>'xxlarge'} %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<%content_for :page_header do%>
<h1>Listing reports</h1>
<%end%>
<table>
  <tr>
    <th>Title</th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= link_to report.title, report %></td>
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :page_header do %>
<h2><%= @report.title %></h2>
<%end%>

<p>
  <b>Notes:</b>
  <%= @report.notes %>
</p>


<% ['This Week','Next Week'].each do |kind| %>
  <h3><%=kind%></h3>
  <ul>
  <% @report.report_items.all(:conditions=>{:kind => kind}, :order => :user_id).each do |report_item| %>
      <li>
        <a class="report_item" data-item_id="<%=report_item.id%>" href="#"><%= report_item.title %> <span class="label"><%= report_item.user.name %></span></a>
      </li>
  <% end %>
  </ul>
<% end %>

<hr />

<%= render 'report_items/form' %>



<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

<div id="editmodal" class="modal hide">
  <div class="modal-header">
    <a href="#" class="close">&times;</a>
    <h3>Edit Task</h3>
  </div>
  <div class="modal-body"></div>
</div>


<script>
$(function(){
  $('.report_item').click(function(){
    $('#editmodal').modal('show');
    $.ajax({url:'/report_items/' + $(this).data('item_id') + '/edit',
    success: function(data){
      $('.modal-body').html(data);
    },
    async: false});
  });
});
</script>

<style>
.modal .popover,
.modal .twipsy {
z-index: 12000;
}
</style>